server:
  port: 8080

spring:
  application:
    name: bets
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS bets
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: bets
    liquibase-schema: bets

management:
  endpoints:
    web:
      exposure:
        include: health,info
